
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from inference_classifier import inferenceClasFunct
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"./assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("915x698")
window.configure(bg = "#CCB7AE")


canvas = Canvas(
    window,
    bg = "#CCB7AE",
    height = 698,
    width = 915,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=inferenceClasFunct,
    relief="flat"
)
button_1.place(
    x=188.0,
    y=431.0,
    width=538.0,
    height=123.0
)

canvas.create_text(
    146.0,
    108.0,
    anchor="nw",
    text="SenamexSLP",
    fill="#A6808D",
    font=("Inter Bold", 96 * -1)
)
window.resizable(False, False)
window.mainloop()
